-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here

-- vim.api.nvim_create_autocmd("VimEnter", {
--   pattern = "*",
--   command = "!kitty @ set-spacing padding-left=0 padding-top=0",
-- })
--
-- vim.api.nvim_create_autocmd("VimLeave", {
--   pattern = "*",
--   command = "!kitty @ set-spacing padding-left=default padding-top=default",
-- })
