-- Vercel theme colors (matching bat/tmTheme)
local colors = {
  bg = "#000000",
  fg = "#eeeeee",
  gray = "#a0a0a0",
  line_highlight = "#1a1a1a",
  selection = "#1f3e70",
  green = "#00cb50",
  pink = "#ff4d8d",
  purple = "#c473fc",
  blue = "#47a8ff",
  light_blue = "#A6B5FF",
  white = "#ffffff",
  red = "#f85149",
  amber = "#d29922",
  diff_add = "#70d9a8",
  diff_delete = "#ff8c85",
}

return {
  {
    "projekt0n/github-nvim-theme",
    lazy = false,
    priority = 1000,
    config = function()
      require("github-theme").setup({
        groups = {
          all = {
            -- Editor
            Normal = { bg = colors.bg, fg = colors.fg },
            NormalFloat = { bg = colors.bg, fg = colors.fg },
            NormalNC = { bg = colors.bg, fg = colors.fg },
            NormalSB = { bg = colors.bg, fg = colors.fg },
            CursorLine = { bg = colors.line_highlight },
            CursorLineNr = { fg = colors.fg },
            LineNr = { fg = colors.gray },
            Visual = { bg = colors.selection },
            VisualNOS = { bg = colors.selection },
            Search = { bg = colors.selection, fg = colors.fg },
            IncSearch = { bg = colors.blue, fg = colors.bg },
            Pmenu = { bg = colors.bg, fg = colors.fg },
            PmenuSel = { bg = colors.line_highlight },
            PmenuThumb = { bg = colors.gray },

            -- Syntax (base vim groups)
            Comment = { fg = colors.gray, italic = true },
            String = { fg = colors.green },
            Character = { fg = colors.fg },
            Number = { fg = colors.white },
            Boolean = { fg = colors.blue },
            Float = { fg = colors.white },
            Identifier = { fg = colors.fg },
            Function = { fg = colors.purple },
            Statement = { fg = colors.pink },
            Conditional = { fg = colors.pink },
            Repeat = { fg = colors.pink },
            Label = { fg = colors.pink },
            Operator = { fg = colors.pink },
            Keyword = { fg = colors.pink },
            Exception = { fg = colors.pink },
            PreProc = { fg = colors.pink },
            Include = { fg = colors.pink },
            Define = { fg = colors.pink },
            Macro = { fg = colors.pink },
            PreCondit = { fg = colors.pink },
            Type = { fg = colors.purple },
            StorageClass = { fg = colors.pink },
            Structure = { fg = colors.fg },
            Typedef = { fg = colors.purple },
            Special = { fg = colors.fg },
            SpecialChar = { fg = colors.green },
            Tag = { fg = colors.blue },
            Delimiter = { fg = colors.fg },
            SpecialComment = { fg = colors.gray },
            Debug = { fg = colors.pink },
            Underlined = { fg = colors.green, underline = true },
            Error = { fg = colors.red },
            Todo = { fg = colors.purple, bold = true },
            Constant = { fg = colors.blue },

            -- Treesitter
            ["@comment"] = { fg = colors.gray, italic = true },
            ["@string"] = { fg = colors.green },
            ["@string.escape"] = { fg = colors.green },
            ["@string.regex"] = { fg = colors.green },
            ["@string.special"] = { fg = colors.fg },
            ["@string.special.url"] = { fg = colors.green },
            ["@character"] = { fg = colors.fg },
            ["@number"] = { fg = colors.white },
            ["@number.float"] = { fg = colors.white },
            ["@boolean"] = { fg = colors.blue },
            ["@constant"] = { fg = colors.blue },
            ["@constant.builtin"] = { fg = colors.white },
            ["@constant.macro"] = { fg = colors.blue },
            ["@variable"] = { fg = colors.fg },
            ["@variable.builtin"] = { fg = colors.light_blue },
            ["@variable.parameter"] = { fg = colors.fg },
            ["@variable.member"] = { fg = colors.fg },
            ["@property"] = { fg = colors.fg },
            ["@function"] = { fg = colors.purple },
            ["@function.builtin"] = { fg = colors.purple },
            ["@function.call"] = { fg = colors.purple },
            ["@function.macro"] = { fg = colors.purple },
            ["@function.method"] = { fg = colors.purple },
            ["@function.method.call"] = { fg = colors.purple },
            ["@constructor"] = { fg = colors.blue },
            ["@keyword"] = { fg = colors.pink },
            ["@keyword.conditional"] = { fg = colors.pink },
            ["@keyword.conditional.ternary"] = { fg = colors.pink },
            ["@keyword.repeat"] = { fg = colors.pink },
            ["@keyword.return"] = { fg = colors.pink },
            ["@keyword.exception"] = { fg = colors.pink },
            ["@keyword.import"] = { fg = colors.pink },
            ["@keyword.export"] = { fg = colors.pink },
            ["@keyword.operator"] = { fg = colors.pink },
            ["@keyword.function"] = { fg = colors.pink },
            ["@keyword.type"] = { fg = colors.pink },
            ["@operator"] = { fg = colors.pink },
            ["@punctuation"] = { fg = colors.fg },
            ["@punctuation.bracket"] = { fg = colors.fg },
            ["@punctuation.delimiter"] = { fg = colors.fg },
            ["@punctuation.special"] = { fg = colors.fg },
            ["@type"] = { fg = colors.purple },
            ["@type.builtin"] = { fg = colors.blue },
            ["@type.definition"] = { fg = colors.purple },
            ["@type.qualifier"] = { fg = colors.pink },
            ["@module"] = { fg = colors.fg },
            ["@attribute"] = { fg = colors.purple },
            ["@tag"] = { fg = colors.blue },
            ["@tag.attribute"] = { fg = colors.purple },
            ["@tag.delimiter"] = { fg = colors.fg },
            ["@tag.builtin"] = { fg = colors.green },

            -- JSX/TSX specific
            ["@constructor.tsx"] = { fg = colors.blue },
            ["@constructor.jsx"] = { fg = colors.blue },
            ["@tag.tsx"] = { fg = colors.blue },
            ["@tag.jsx"] = { fg = colors.blue },
            ["@tag.delimiter.tsx"] = { fg = colors.fg },
            ["@tag.delimiter.jsx"] = { fg = colors.fg },
            ["@punctuation.bracket.tsx"] = { fg = colors.fg },
            ["@punctuation.bracket.jsx"] = { fg = colors.fg },
            -- Markup (markdown files only)
            ["@markup.heading"] = { fg = colors.fg },
            ["@markup.heading.markdown"] = { fg = colors.purple, bold = true },
            ["@markup.heading.1.markdown"] = { fg = colors.purple, bold = true },
            ["@markup.heading.2.markdown"] = { fg = colors.purple, bold = true },
            ["@markup.heading.3.markdown"] = { fg = colors.purple, bold = true },
            ["@markup.heading.4.markdown"] = { fg = colors.purple, bold = true },
            ["@markup.heading.5.markdown"] = { fg = colors.purple, bold = true },
            ["@markup.heading.6.markdown"] = { fg = colors.purple, bold = true },
            ["@markup.bold"] = { bold = true },
            ["@markup.italic"] = { italic = true },
            ["@markup.link"] = { fg = colors.green, underline = true },
            ["@markup.link.url"] = { fg = colors.green, underline = true },
            ["@markup.raw"] = { fg = colors.fg },
            ["@markup.raw.markdown"] = { fg = colors.green },
            ["@markup.raw.markdown_inline"] = { fg = colors.green },
            ["@markup.quote"] = { fg = colors.gray, italic = true },
            ["@markup.list"] = { fg = colors.blue },

            -- JSX text content should be fg
            ["@none.tsx"] = { fg = colors.fg },
            ["@none.jsx"] = { fg = colors.fg },
            ["@text"] = { fg = colors.fg },
            ["@text.tsx"] = { fg = colors.fg },
            ["@text.jsx"] = { fg = colors.fg },
            ["@markup.raw.block.tsx"] = { fg = colors.fg },
            ["@markup.raw.block.jsx"] = { fg = colors.fg },

            -- MDX specific
            ["@punctuation.bracket.mdx"] = { fg = colors.fg },
            ["@punctuation.delimiter.mdx"] = { fg = colors.fg },
            ["@constructor.mdx"] = { fg = colors.blue },
            ["@tag.mdx"] = { fg = colors.blue },
            ["@tag.builtin.mdx"] = { fg = colors.green },
            ["@tag.delimiter.mdx"] = { fg = colors.fg },
            ["@tag.attribute.mdx"] = { fg = colors.purple },
            ["@diff.plus"] = { fg = colors.diff_add },
            ["@diff.minus"] = { fg = colors.diff_delete },

            -- LSP semantic tokens
            ["@lsp.type.class"] = { fg = colors.purple },
            ["@lsp.type.decorator"] = { fg = colors.purple },
            ["@lsp.type.enum"] = { fg = colors.purple },
            ["@lsp.type.enumMember"] = { fg = colors.blue },
            ["@lsp.type.function"] = { fg = colors.purple },
            ["@lsp.type.interface"] = { fg = colors.purple },
            ["@lsp.type.macro"] = { fg = colors.purple },
            ["@lsp.type.method"] = { fg = colors.purple },
            ["@lsp.type.namespace"] = { fg = colors.fg },
            ["@lsp.type.parameter"] = { fg = colors.fg },
            ["@lsp.type.property"] = { fg = colors.fg },
            ["@lsp.type.struct"] = { fg = colors.purple },
            ["@lsp.type.type"] = { fg = colors.purple },
            ["@lsp.type.typeParameter"] = { fg = colors.blue },
            ["@lsp.type.variable"] = { fg = colors.blue },
            ["@lsp.mod.readonly"] = { fg = colors.blue },
            ["@lsp.mod.defaultLibrary"] = {},
            ["@lsp.typemod.class.defaultLibrary"] = { fg = colors.purple },
            ["@lsp.typemod.function.defaultLibrary"] = { fg = colors.purple },
            ["@lsp.typemod.variable.defaultLibrary"] = { fg = colors.fg },

            -- TypeScript/JavaScript specific
            -- Imported identifiers are text color, const variables are blue
            ["@lsp.type.variable.typescript"] = { fg = colors.fg },
            ["@lsp.type.variable.typescriptreact"] = { fg = colors.fg },
            ["@lsp.type.variable.javascript"] = { fg = colors.fg },
            ["@lsp.type.variable.javascriptreact"] = { fg = colors.fg },
            -- const/readonly variables get blue (constant color)
            ["@lsp.typemod.variable.readonly.typescript"] = { fg = colors.blue },
            ["@lsp.typemod.variable.readonly.typescriptreact"] = { fg = colors.blue },
            ["@lsp.typemod.variable.readonly.javascript"] = { fg = colors.blue },
            ["@lsp.typemod.variable.readonly.javascriptreact"] = { fg = colors.blue },
            ["@lsp.typemod.variable.local.typescript"] = { fg = colors.blue },
            ["@lsp.typemod.variable.local.typescriptreact"] = { fg = colors.blue },
            ["@lsp.typemod.variable.local.javascript"] = { fg = colors.blue },
            ["@lsp.typemod.variable.local.javascriptreact"] = { fg = colors.blue },

            -- Rust specific (variables stay text color, types are purple)
            ["@lsp.type.variable.rust"] = { fg = colors.fg },
            ["@lsp.type.parameter.rust"] = { fg = colors.fg },
            ["@lsp.type.namespace.rust"] = { fg = colors.fg },
            ["@lsp.type.enumMember.rust"] = { fg = colors.purple },
            ["@keyword.coroutine.rust"] = { fg = colors.pink },
            ["@punctuation.delimiter.rust"] = { fg = colors.pink },
            ["@operator.rust"] = { fg = colors.pink },

            -- Git signs
            GitSignsAdd = { fg = colors.diff_add },
            GitSignsChange = { fg = colors.blue },
            GitSignsDelete = { fg = colors.diff_delete },
            DiffAdd = { bg = "#0d380d" },
            DiffChange = { bg = "#38380d" },
            DiffDelete = { bg = "#380d0d" },
            DiffText = { bg = "#4a4a1f" },

            -- mini.diff
            MiniDiffSignAdd = { fg = "#66c266" },
            MiniDiffSignChange = { fg = "#c2c266" },
            MiniDiffSignDelete = { fg = "#c26666" },
            MiniDiffOverAdd = { bg = "#0d380d" },
            MiniDiffOverChange = { bg = "#38380d" },
            MiniDiffOverDelete = { bg = "#380d0d" },
            MiniDiffOverContext = { bg = "#38380d" },

            -- Diagnostics
            DiagnosticError = { fg = colors.red },
            DiagnosticWarn = { fg = colors.amber },
            DiagnosticInfo = { fg = colors.blue },
            DiagnosticHint = { fg = colors.purple },

            -- WhichKey
            WhichKey = { fg = colors.fg },
            WhichKeyDesc = { fg = colors.fg },
            WhichKeyGroup = { fg = colors.light_blue },
            WhichKeyValue = { fg = colors.gray },
          },
        },
      })

      vim.cmd("colorscheme github_dark_default")
    end,
  },
}
