-- Vercel theme colors (matching bat/tmTheme)
local colors = {
  bg = "#000000",
  fg = "#eeeeee",
  gray = "#a0a0a0",
  line_highlight = "#1a1a1a",
  selection = "#1f3e70",
  green = "#00cb50",
  pink = "#ff4d8d",
  purple = "#c473fc",
  blue = "#47a8ff",
  light_blue = "#A6B5FF",
  white = "#ffffff",
  red = "#ff0000",
  diff_add = "#70d9a8",
  diff_delete = "#ff8c85",
}

return {
  {
    "projekt0n/github-nvim-theme",
    lazy = false,
    priority = 1000,
    config = function()
      require("github-theme").setup({
        groups = {
          all = {
            -- Editor
            Normal = { bg = colors.bg, fg = colors.fg },
            NormalFloat = { bg = colors.bg, fg = colors.fg },
            NormalNC = { bg = colors.bg, fg = colors.fg },
            NormalSB = { bg = colors.bg, fg = colors.fg },
            CursorLine = { bg = colors.line_highlight },
            CursorLineNr = { fg = colors.fg },
            LineNr = { fg = colors.gray },
            Visual = { bg = colors.selection },
            VisualNOS = { bg = colors.selection },
            Search = { bg = colors.selection, fg = colors.fg },
            IncSearch = { bg = colors.blue, fg = colors.bg },
            Pmenu = { bg = colors.bg, fg = colors.fg },
            PmenuSel = { bg = colors.line_highlight },
            PmenuThumb = { bg = colors.gray },

            -- Syntax (base vim groups)
            Comment = { fg = colors.gray, italic = true },
            String = { fg = colors.green },
            Character = { fg = colors.green },
            Number = { fg = colors.white },
            Boolean = { fg = colors.white },
            Float = { fg = colors.white },
            Identifier = { fg = colors.fg },
            Function = { fg = colors.purple },
            Statement = { fg = colors.pink },
            Conditional = { fg = colors.pink },
            Repeat = { fg = colors.pink },
            Label = { fg = colors.pink },
            Operator = { fg = colors.pink },
            Keyword = { fg = colors.pink },
            Exception = { fg = colors.pink },
            PreProc = { fg = colors.pink },
            Include = { fg = colors.pink },
            Define = { fg = colors.pink },
            Macro = { fg = colors.pink },
            PreCondit = { fg = colors.pink },
            Type = { fg = colors.blue },
            StorageClass = { fg = colors.pink },
            Structure = { fg = colors.purple },
            Typedef = { fg = colors.blue },
            Special = { fg = colors.purple },
            SpecialChar = { fg = colors.light_blue },
            Tag = { fg = colors.green },
            Delimiter = { fg = colors.fg },
            SpecialComment = { fg = colors.gray },
            Debug = { fg = colors.pink },
            Underlined = { fg = colors.green, underline = true },
            Error = { fg = colors.red },
            Todo = { fg = colors.purple, bold = true },
            Constant = { fg = colors.blue },

            -- Treesitter
            ["@comment"] = { fg = colors.gray, italic = true },
            ["@string"] = { fg = colors.green },
            ["@string.escape"] = { fg = colors.green },
            ["@string.regex"] = { fg = colors.green },
            ["@character"] = { fg = colors.green },
            ["@number"] = { fg = colors.white },
            ["@number.float"] = { fg = colors.white },
            ["@boolean"] = { fg = colors.white },
            ["@constant"] = { fg = colors.blue },
            ["@constant.builtin"] = { fg = colors.white },
            ["@constant.macro"] = { fg = colors.blue },
            ["@variable"] = { fg = colors.fg },
            ["@variable.builtin"] = { fg = colors.light_blue },
            ["@variable.parameter"] = { fg = colors.fg },
            ["@variable.member"] = { fg = colors.fg },
            ["@property"] = { fg = colors.fg },
            ["@function"] = { fg = colors.purple },
            ["@function.builtin"] = { fg = colors.purple },
            ["@function.call"] = { fg = colors.purple },
            ["@function.macro"] = { fg = colors.purple },
            ["@function.method"] = { fg = colors.purple },
            ["@function.method.call"] = { fg = colors.purple },
            ["@constructor"] = { fg = colors.purple },
            ["@keyword"] = { fg = colors.pink },
            ["@keyword.conditional"] = { fg = colors.pink },
            ["@keyword.repeat"] = { fg = colors.pink },
            ["@keyword.return"] = { fg = colors.pink },
            ["@keyword.exception"] = { fg = colors.pink },
            ["@keyword.import"] = { fg = colors.pink },
            ["@keyword.export"] = { fg = colors.pink },
            ["@keyword.operator"] = { fg = colors.pink },
            ["@keyword.function"] = { fg = colors.pink },
            ["@operator"] = { fg = colors.pink },
            ["@punctuation"] = { fg = colors.fg },
            ["@punctuation.bracket"] = { fg = colors.fg },
            ["@punctuation.delimiter"] = { fg = colors.fg },
            ["@punctuation.special"] = { fg = colors.pink },
            ["@type"] = { fg = colors.blue },
            ["@type.builtin"] = { fg = colors.blue },
            ["@type.definition"] = { fg = colors.purple },
            ["@type.qualifier"] = { fg = colors.pink },
            ["@module"] = { fg = colors.fg },
            ["@attribute"] = { fg = colors.purple },
            ["@tag"] = { fg = colors.green },
            ["@tag.attribute"] = { fg = colors.purple },
            ["@tag.delimiter"] = { fg = colors.fg },
            ["@markup.heading"] = { fg = colors.purple, bold = true },
            ["@markup.bold"] = { fg = colors.pink, bold = true },
            ["@markup.italic"] = { italic = true },
            ["@markup.link"] = { fg = colors.green, underline = true },
            ["@markup.link.url"] = { fg = colors.green, underline = true },
            ["@markup.raw"] = { fg = colors.green },
            ["@markup.quote"] = { fg = colors.gray, italic = true },
            ["@markup.list"] = { fg = colors.blue },
            ["@diff.plus"] = { fg = colors.diff_add },
            ["@diff.minus"] = { fg = colors.diff_delete },

            -- LSP semantic tokens
            ["@lsp.type.class"] = { fg = colors.purple },
            ["@lsp.type.decorator"] = { fg = colors.purple },
            ["@lsp.type.enum"] = { fg = colors.purple },
            ["@lsp.type.enumMember"] = { fg = colors.blue },
            ["@lsp.type.function"] = { fg = colors.purple },
            ["@lsp.type.interface"] = { fg = colors.purple },
            ["@lsp.type.macro"] = { fg = colors.purple },
            ["@lsp.type.method"] = { fg = colors.purple },
            ["@lsp.type.namespace"] = { fg = colors.fg },
            ["@lsp.type.parameter"] = { fg = colors.fg },
            ["@lsp.type.property"] = { fg = colors.fg },
            ["@lsp.type.struct"] = { fg = colors.purple },
            ["@lsp.type.type"] = { fg = colors.blue },
            ["@lsp.type.typeParameter"] = { fg = colors.blue },
            ["@lsp.type.variable"] = { fg = colors.fg },
            ["@lsp.mod.readonly"] = { fg = colors.blue },
            ["@lsp.mod.defaultLibrary"] = { fg = colors.light_blue },

            -- Git signs
            GitSignsAdd = { fg = colors.diff_add },
            GitSignsChange = { fg = colors.blue },
            GitSignsDelete = { fg = colors.diff_delete },
            DiffAdd = { bg = "#0d2818" },
            DiffChange = { bg = "#1a1a1a" },
            DiffDelete = { bg = "#2d1215" },
            DiffText = { bg = "#1f3e70" },

            -- Diagnostics
            DiagnosticError = { fg = colors.red },
            DiagnosticWarn = { fg = colors.pink },
            DiagnosticInfo = { fg = colors.blue },
            DiagnosticHint = { fg = colors.purple },
          },
        },
      })

      vim.cmd("colorscheme github_dark_default")
    end,
  },
}
